### ISSUE TITLE
Ring of Sponge deletes waterlogged blocks

### ISSUE THREAD

**Issue by Setadokalo** [Focamacho/RingsOfAscension#12]
While running around using the ring of sponge looking for sunken ships, I noticed that it destroys waterlogged blocks - not that big of an issue for most, but it's pretty noticeable and annoying when it destroys a chest and spams the area with a bunch of items.

**Comment by focamacho** [comment]
Fixed in the latest version. Thanks for the report!

**Forge:**
1.15.2: https://www.curseforge.com/minecraft/mc-mods/rings-of-ascension/files/3023715
1.16.1: https://www.curseforge.com/minecraft/mc-mods/rings-of-ascension/files/3023716

**Fabric:**
1.15.2: https://www.curseforge.com/minecraft/mc-mods/fabric-rings-of-ascension/files/3023718
1.16.1: https://www.curseforge.com/minecraft/mc-mods/fabric-rings-of-ascension/files/3023724
